SELECT *
FROM
CUSTOMERS

INSERT INTO CUSTOMERS
(CUSTOMERNAME,CITY, BIRTHDATE,DISTRICT, GENDER )
VALUES 
('MEHMET ÖZAL','ANTALYA','1990-12-21','ALANYA','E')
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY, DISTRICT, BIRTHDATE, GENDER) 
VALUES ('GÜLCÝHAN GÜLMEZ','ÝSTANBUL','ESENLER','2000-12-16','K')
SELECT * FROM CUSTOMERS
UPDATE CUSTOMERS
SET NATION='TR', AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())
SELECT* FROM CUSTOMERS
DELETE FROM CUSTOMERS
WHERE ID>=7
SELECT *FROM CUSTOMERS
WHERE AGE BETWEEN 20 AND 30
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'S%'
SELECT* FROM CUSTOMERS
UPDATE CUSTOMERS SET GENDER='ERKEK'WHERE GENDER ='E'
UPDATE CUSTOMERS SET GENDER ='KADIN' WHERE GENDER ='K'
DELETE CUSTOMERS WHERE ID=9
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY, DISTRICT, BIRTHDATE, GENDER) 
VALUES ('ZAHÝDENUR GÖKAY','KASTAMONU','GAZÝOSMANPAÞA','2002-10-11','K') 
SELECT *FROM CUSTOMERS